[package]
name = "erp-api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
diesel = { version = "2.2.10", features = ["mysql", "r2d2"] }
dotenv = "0.15.0"
env_logger = "0.11.8"
jsonwebtoken = "9.3.1"
log = "0.4.27"
meilisearch-sdk = "0.28.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
uuid = { version = "1.17.0", features = ["serde", "v4"] }

[dev-dependencies]
reqwest = { version = "0.12.19", features = ["json"] }
serial_test = "3.2.0"
