services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
      - meilisearch
    environment:
      - DATABASE_URL=mysql://user:password@mariadb:3306/erp_db
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_API_KEY=masterKey
      - APP_ENV=production
    networks:
      - erp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/inventory/search"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=erp_db
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - erp-network
    healthcheck:
        test:
            - CMD
            - healthcheck.sh
            - '--connect'
            - '--innodb_initialized'
        retries: 3
        timeout: 5s

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_MASTER_KEY=masterKey
    ports:
      - "7700:7700"
    volumes:
      - meilisearch-data:/meili_data
    networks:
      - erp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  erp-network:
    driver: bridge

volumes:
  mariadb-data:
  meilisearch-data: