[package]
name = "search"
version = "0.1.0"
edition = "2024"

[dependencies]
meilisearch-sdk = "0.28.0"
entity = { path = "../entity" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"