[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "1.1.13", features = ["with-chrono"] }
serde = { version = "1.0.219", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
utoipa = { version = "5.3.1", features = ["chrono"] }