[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { version = "0.14.0", features = ["yaml"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_derive = "1.0.203"
toml = "0.8.14"