[package]
name = "page"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.11.0"
inertia-rust = { version = "2", features = ["actix", "vite-hbs-template-resolver", "actix-validator"] }
vite-rust = { version = "0.2" }
serde_json = "1.0.140"
